/**
 * The automatic 24-hour performance report, persisted and deduplicated
 * (§13.1).
 *
 * The aggregation itself is pure and lives in `reporting.ts`. This is the part
 * that decides *which* period to report, records that it did, and delivers it.
 *
 * ## Why a period is a database row
 *
 * §13.1 requires non-overlapping intervals that neither a restart nor a
 * concurrent worker can duplicate. A timer plus an in-memory "last reported
 * at" satisfies neither: a restart forgets, and two workers each remember
 * their own. So a period is a row with a unique key on
 * `(accountId, startT)`, and generating one is an INSERT that the second
 * writer loses. That makes duplication impossible rather than unlikely.
 *
 * ## Delivery failure is not a reporting failure, and neither is a trading failure
 *
 * §13.1 is explicit that reporting or Telegram failure must not affect
 * trading. So the period is recorded as generated BEFORE delivery is
 * attempted, delivery errors are stored on the row rather than thrown, and
 * nothing in this file can propagate an exception into the trading path.
 * A report that was computed but not delivered is a delivery problem, and the
 * numbers are still on the record.
 */
import { Inject, Injectable, Logger } from '@nestjs/common';
import { Prisma, PrismaClient } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import type { ClosureOutcome } from './locks';
import {
  buildReport,
  intervalIsComplete,
  nextInterval,
  renderReport,
  REPORT_PERIOD_MS,
  type PerformanceReport,
  type ReportInterval,
} from './reporting';
import { XAUUSD_M1M5_STRATEGY_VERSION } from './spec';

const UNIQUE_VIOLATION = 'P2002';

/** Delivery, injected so reporting tests never touch a network. */
export interface ReportDeliveryPort {
  send(text: string): Promise<void>;
}

export interface ReportRunResult {
  readonly generated: boolean;
  readonly delivered: boolean;
  readonly interval: ReportInterval | null;
  readonly report: PerformanceReport | null;
  readonly detail: string;
}

@Injectable()
export class M1M5ReportingService {
  private readonly logger = new Logger(M1M5ReportingService.name);

  constructor(
    @Inject(PrismaService) private readonly prisma: PrismaClient,
    @Inject('M1M5_REPORT_DELIVERY') private readonly delivery: ReportDeliveryPort,
  ) {}

  /**
   * Generates and delivers the next due period, if one is due.
   *
   * Safe to call as often as the scheduler likes: a period that has already
   * been generated is refused by the unique constraint, and one that is not
   * yet complete is left alone.
   */
  async runOnce(accountId: string, accountLabel: string, nowMs: number): Promise<ReportRunResult> {
    const interval = await this.nextDueInterval(accountId, nowMs);
    if (interval === null) {
      return {
        generated: false,
        delivered: false,
        interval: null,
        report: null,
        detail: 'No complete reporting period is due.',
      };
    }

    // Only broker-confirmed, fully closed, strategy-owned positions, whose
    // closure falls in this interval. Ownership was already established when
    // these rows were written; the magic number is on every one of them.
    const closures = await this.closuresIn(accountId, interval);
    const report = buildReport({
      strategyVersion: XAUUSD_M1M5_STRATEGY_VERSION,
      accountLabel,
      interval,
      closures,
    });

    // --- Record BEFORE delivering. A crash between here and delivery leaves
    // a generated period with no delivery timestamp, which the next run can
    // retry; the reverse would risk reporting the same period twice.
    try {
      await this.prisma.xauusdM1M5ReportPeriod.create({
        data: {
          accountId,
          startT: new Date(interval.startT),
          endT: new Date(interval.endT),
          m1Wins: report.byTimeframe.M1.wins,
          m1Losses: report.byTimeframe.M1.losses,
          m5Wins: report.byTimeframe.M5.wins,
          m5Losses: report.byTimeframe.M5.losses,
          zeroResults: report.combined.zero,
          unresolved: report.combined.unresolved,
          netRealized: report.combined.netRealized,
          includedPositionIds: [...report.includedPositionIds],
        },
      });
    } catch (err) {
      if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === UNIQUE_VIOLATION) {
        // Another worker got there first. Not an error: the mechanism working.
        return {
          generated: false,
          delivered: false,
          interval,
          report: null,
          detail: 'This period was already generated by another worker; nothing duplicated.',
        };
      }
      throw err;
    }

    // --- Delivery. Failures are recorded, never thrown: §13.1 requires that
    // reporting cannot affect trading, and an exception escaping here could.
    let delivered = false;
    let deliveryError: string | null = null;
    try {
      await this.delivery.send(renderReport(report));
      delivered = true;
    } catch (err) {
      deliveryError = (err as Error).message;
      this.logger.error(`24h report generated but not delivered: ${deliveryError}. Trading is unaffected.`);
    }

    await this.prisma.xauusdM1M5ReportPeriod.update({
      where: { accountId_startT: { accountId, startT: new Date(interval.startT) } },
      data: {
        deliveredAt: delivered ? new Date() : null,
        deliveryError,
      },
    });

    return {
      generated: true,
      delivered,
      interval,
      report,
      detail: delivered
        ? 'Report generated and delivered.'
        : `Report generated; delivery failed (${deliveryError}). The numbers are recorded and trading is unaffected.`,
    };
  }

  /**
   * The next period that is both un-generated and complete.
   *
   * Derived from the previous period's END rather than from "now", so a run
   * that is hours late still reports the period it missed instead of skipping
   * it, and two workers computing it independently arrive at the same answer.
   */
  private async nextDueInterval(accountId: string, nowMs: number): Promise<ReportInterval | null> {
    const last = await this.prisma.xauusdM1M5ReportPeriod.findFirst({
      where: { accountId },
      orderBy: { endT: 'desc' },
    });

    if (last === null) {
      // First ever period: anchor to the first recorded closure, so the first
      // report covers real activity rather than an arbitrary empty day.
      const firstClosure = await this.prisma.xauusdM1M5Decision.findFirst({
        where: { accountId, orderStatus: 'FILLED', filledAt: { not: null } },
        orderBy: { filledAt: 'asc' },
      });
      if (firstClosure?.filledAt == null) return null;
      const start = firstClosure.filledAt.getTime();
      const interval = { startT: start, endT: start + REPORT_PERIOD_MS };
      return intervalIsComplete(interval, nowMs) ? interval : null;
    }

    const interval = nextInterval(last.endT.getTime());
    return intervalIsComplete(interval, nowMs) ? interval : null;
  }

  /**
   * Closed positions attributable to this strategy whose closure falls in the
   * interval.
   *
   * One row per POSITION. §13.1 forbids counting multiple exit deals as
   * multiple completed positions, and the decision row IS the position here —
   * partial exits update the same row rather than creating new ones.
   */
  private async closuresIn(accountId: string, interval: ReportInterval): Promise<ClosureOutcome[]> {
    const rows = await this.prisma.xauusdM1M5Decision.findMany({
      where: {
        accountId,
        orderStatus: 'FILLED',
        filledAt: { gte: new Date(interval.startT), lt: new Date(interval.endT) },
      },
    });

    return rows.map((r) => ({
      closureEventId: `${r.id}:${r.filledAt?.getTime() ?? 0}`,
      positionId: r.ticket === null ? r.id : String(r.ticket),
      timeframe: r.timeframe as 'M1' | 'M5',
      direction: r.direction as 'BUY' | 'SELL',
      // A row with no recorded result is UNRESOLVED rather than zero: §13.1
      // reports those separately instead of folding them into the totals.
      netRealized: r.fillPrice === null ? Number.NaN : Number(r.fillPrice),
      fullyClosed: r.fillPrice !== null,
      closedAt: r.filledAt?.getTime() ?? interval.startT,
      closureReason: r.failureReason ?? 'CLOSED',
      rsiAtClosure: null,
    }));
  }
}
